import Navigation from "@/components/Navigation";
import "./globals.css";
import { Inter } from "next/font/google";
import { GlobalProvider } from "@/context/GlobalState";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BuyRecorder",
  description: "Generated by create next app",
  keywords: "next, react, javascript",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://bootswatch.com/5/pulse/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        ></link>
      </head>
      <body className={inter.className}>
        <GlobalProvider>
          <Navigation />
          <div className="container p-4">{children}</div>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossOrigin="anonymous"
            async
          ></script>
        </GlobalProvider>
      </body>
    </html>
  );
}
